### ISSUE TITLE
Typo line 453 GoodVibes.py "trhular"

### ISSUE THREAD

**Issue by DSVA** [patonlab/GoodVibes#1]
In line 453 there's a typo in the error message

`else: log.Fatal("\n   FATAL ERROR: Wrong number of arguments used.\n   Correct format: GoodVibes.py (-qh grimme/trhular) (-f cutoff_freq) (-t temp) (-c concn) (-v scalefactor) g09_output_file(s)\n")`

truhlar is the correct command, not trhular.

**Comment by bobbypaton** [comment]
Whoops! Reverted back to an old typographical error when updating something else. Thanks for spotting, now fixed
