### ISSUE TITLE
Counterpoise corrected opt freq jobs.

### ISSUE THREAD

**Issue by DSVA** [patonlab/GoodVibes#11]
Hi,
if goodvibes is used on a counterpoise corrected opt/freq calculation it seems to correctly pull the frequency calculation data but it takes the E value from the last fragment.

This might be more difficult to fix, is it possible that the corrected thermodynamic data (calculated "T.qh-S/au")  is nevertheless correct? Or does it use some wrong molecular weight/structure to calculate this correction?

Thank you!

**Comment by bobbypaton** [comment]
Hmm - didn't know it was possible to perform a counterpoise-corrected optimization in Gaussian. Presumably you would want the CP-corrected energy and then to add the thermal corrections in the usual way? This is the fix I've made. 

The rotational and vibrational temperatures will still be molecular properties, and they are calculated for the optimized structure, so the thermal corrections produced by GoodVibes should be correct. You can always check for erroneous results by setting the frequency cutoff to zero: in this case, the quasi-harmonic results will be equal to the harmonic results, and identical to those contained in the output file.
