### ISSUE TITLE
Problems with pip release (2.0.1)

### ISSUE THREAD

**Issue by theochemtheo** [patonlab/GoodVibes#12]
Hi,

I just tried using pip to install GoodVibes and couldn't get it to work as described in the documentation. For example, if I try the following command:
```
[~]: python -m goodvibes -h
/usr/local/anaconda3/bin/python: No module named goodvibes.__main__; 'goodvibes' is a package and cannot be directly executed
```
It also doesn't work if I try to run `GoodVibes.py` directly from the site packages directory, like this:
```
[~/Documents/test]: sudo python3 /usr/local/anaconda3/lib/python3.6/site-packages/goodvibes/GoodVibes.py test.log
   GoodVibes v2.0.1 2018/05/15 17:52:30
   REF: Funes-Ardoiz, I.; Paton, R. S. (2016). GoodVibes: GoodVibes v1.0.2. http://doi.org/10.5281/zenodo.595246

   Temperature = 298.15 Kelvin   Pressure = 1 atmTraceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.6/site-packages/goodvibes/GoodVibes.py", line 438, in <module>
    if l_o_t[0].upper().find(scal['level'].upper()) > -1 or l_o_t[0].upper().find(scal['level'].replace("-","").upper()) > -1:
TypeError: must be str, not bytes
```
(Although it is possible to get the -h/--help command to work this way)

I tested this on macOS with anaconda python 3.6, as well as on openSUSE Linux with python 3.4.

That said, when I cloned the current repository and added it to my $PYTHONPATH, everything worked fine.

Thanks,

Theo

**Comment by bobbypaton** [comment]
Thanks - I've updated the version number to 2.0.2 since there were several changes made which allowed the code to be run as a module which had not been updated to 2.0.1 on pipy. 

'pip install goodvibes' should now give you the same result as cloning and adding to the $PYTHONPATH
