### ISSUE TITLE
Things to include in GV

### ISSUE THREAD

**Issue by jvalegre** [patonlab/GoodVibes#14]
(1) In the top part of the output file with the option details, can you make the program write the keywords used to run GoodVibes? (ie python GoodVibes.py -t 300.15 --spc QZ)

(2) Can you make the program not crush when a .log file does not have an associated _QZ file? It would be great that the program showed the error in the output file but it don´t stop working

(3) Include compatibility with COSMO-RS (reminder just in case)

(4) Include Boltzmann average G along with Bolztmann probabilities

**Comment by bobbypaton** [comment]
(1) done - now prints the options which were requested 

(2) done 

(3) done: --cosmo option is now functional

(4) - this will take longer, since need to figure out how to assign which structures are conformers and which are not

**Comment by bobbypaton** [comment]
all done
