### ISSUE TITLE
Bav = 10.0e-44

### ISSUE THREAD

**Issue by pascalfriederich** [patonlab/GoodVibes#24]
Dear GoodVibes developers,

I tried to reproduce the entropy contributions in the low frequency limit (Grimme, DOI: 10.1002/chem.201200497) and I discovered that you are using a value of BAV of
10.0e-44 (line 1922 in GoodVibes.py) while Grimme suggested in his paper to use 1e-44.
Was it your intention to change this value or just a typo in the code?

Best regards,
Pascal Friederich

**Comment by bobbypaton** [comment]
Good spot, thanks! I played around with this value to see its effect and it's possible that it got changed at some point from the value in Grimme's original CEJ paper. In testing, changing by an order of magnitude didn't seem to give rise to noticeable effects - in this case, I have now changed it back to 1e-44, which for our systems leads to a difference of around 2 microH (0.001 kcal/mol) in free energy at 298K.

**Comment by bobbypaton** [comment]
When we played around with B(av) between 1e-45 to 1e-43 (DOI: 10.1021/acs.joc.8b02436) the variation on the absolute free energies was on the order of 0.1 kcal/mol, although for free energy differences the effect was about 0.01 kcal/mol.

**Comment by pascalfriederich** [comment]
Thank you!
