### ISSUE TITLE
Supplying Single point energy not in Gaussian format

### ISSUE THREAD

**Issue by xiki-tempula** [patonlab/GoodVibes#26]
The excellent disk management feature of ORCA makes it a very attractive tool for computing single point energy. For small molecules, the gaussian postHF computation can take several TB of disk space while ORCA only takes several hundred GB. So I wonder if it is possible to supply ORCA file or input manually the single point energy file with the Gaussian opt/freq output file?

**Comment by luchini18** [comment]
Are you trying to apply an ORCA single point energy calculation to a gaussian opt/freq? If so, GoodVibes will recognize single point calculations in the same directory by their filename and the option specified.  For example, you could use `python -m goodvibes file.log --spc DLPNO` where `file.log` is your gaussian file and `file_DLPNO.out` is your ORCA calculation in the same directory.

**Comment by xiki-tempula** [comment]
@luchini18 Exactly what I want. Thank you.
