### ISSUE TITLE
How to cite goodvibe?

### ISSUE THREAD

**Issue by xiki-tempula** [patonlab/GoodVibes#28]
I will surely cite the underlying method but I'm not quite sure of what is a good way of citing goodvide.

**Comment by luchini18** [comment]
Hi, thanks for your support! The following citation is typically used for journal articles:
GoodVibes Version 3.0.1. Zenodo. http://doi.org/10.5281/zenodo.595246

The DOI helps us to track usage, so please include this in the citation, thanks!
