### ISSUE TITLE
Media keyword

### ISSUE THREAD

**Issue by medvedev-m** [patonlab/GoodVibes#33]
Hello!

Could you, please, explain, what is the "entropy correction to calculations done on solvent molecules calculated from their standard concentration", which is requested with --media keyword? Is there any reference to it?

Best regards,
Michael G. Medvedev

**Comment by luchini18** [comment]
Hi Michael,
When calculating standard state free energies (G<sup>o</sup>), the IUPAC specifies that the standard concentration used (c<sup>o</sup>) should be 1M for calculations of reagents in solution and 1 atm (L mol<sup>-1</sup>) for gas phase (see [doi.org/10.1351/goldbook.S05925](https://doi.org/10.1351/goldbook.S05925)). Use of standard state thermodynamic values for computational studies is emphasized in [doi.org/10.1021/jp802665d](https://doi.org/10.1021/jp802665d). GoodVibes can calculate standard concentrations for different media specified in the readme, provided an output calculation file for the solvent. 
Hope this is helpful!
Guilian Luchini

**Comment by bobbypaton** [comment]
With media keyword, we have some solvents for which we have coded the concentration based on their density (eg water is 55 mol/l). The effect on the free energy appears in the translational entropy term. I believe the recent review from Harvey, himo, maseras, Perrin in acs catalysis talks about making such corrections.

**Comment by medvedev-m** [comment]
Thank you for the explanation! 

It seems that "--media" only works correctly when "-p 1" is set (or assumed). So it is impossible to use it along with "-c" which could be important when working with several files simultaneously (e.g. GoodVibes.py -q -c 1 --media h2o *.log). This is likely because --media just adds an appropriate constant for getting from "-p 1" to "-c 55.5", exactly as shown in 10.1021/acscatal.9b01537. 

Perhaps, it could prove useful to just switch Solvent concentration to the appropriate value, ignoring the "-c" keyword for it, while using the input concentration for all other entries.

Best regards,
Michael G. Medvedev

**Comment by luchini18** [comment]
Thanks for the input, the --media keyword will now apply to specifically the solvent molecule, and if the -c option is specified, the specified concentration will apply to all other molecules.
