### ISSUE TITLE
How to decide Freuency (-f and --fs) while using GoodVibes (I am new in Quantam)

### ISSUE THREAD

**Issue by nileshjchoudhary** [patonlab/GoodVibes#38]
Dear Prof. Paton lab, 
Thanks for the great package,
I am using it for  Quasi-harmonic entropy correction and enthalpy correction" for gaussian output(transition state)
Now, I am confused about frequency.  
-f FREQ_CUTOFF        Cut-off frequency for both entropy and enthalpy (wavenumbers) (default = 100)
  --fs S_FREQ_CUTOFF    Cut-off frequency for entropy (wavenumbers) (default =100)
  --fh H_FREQ_CUTOFF    Cut-off frequency for enthalpy (wavenumbers) (default = 100)

How to decide it should be 100 150 or any number
While we are having many vibrational frequency including -negetive one(for ts)

**Comment by jvalegre** [comment]
Dear Nilesh,

Thanks for using the program! The default number used as the frequency cut-off (100 cm-1) comes from the original paper of the quasi-harmonic correction from Grimme (https://doi.org/10.1002/chem.201200497). You can read more about the impact of using different frequency cut-offs in the GoodVibes paper (https://f1000research.com/articles/9-291).

To be honest, as far as the cut-off is within reasonable limits you'll have similar results (i.e. using 50 or 150 cm-1 will lead to very similar results most of the time).

Also, be aware that the quasi-harmonic correction for enthalpy from Head-Gordon and coworkers was designed for measuring adsorption enthalpies (original paper for more information --> https://pubs.acs.org/doi/10.1021/jp509921r). If you are studying a reaction mechanism, I would not include it, and I would just use the quasi-harmonic entropy correction. The imaginary frequency you mentioned coming from the TS is ignored for calculating thermodynamic corrections (imaginary frequencies are also ignored in Gaussian).

Hope this helps!
Juan

**Comment by nileshjchoudhary** [comment]
Dear jvalegre, Thanks for answering. also adding comment about, a reaction mechanism,
This is great help for me. I am a learner. I will read suggested papers.

**Comment by nileshjchoudhary** [comment]
Dear Jvalegre,
I am searching reason behind this statement  
_"If you are studying a reaction mechanism, I would not include it, and I would just use the quasi-harmonic entropy correction."_ 

Is that mean reaction mechanism does not require entahlpy correction? and they why ?
Why only we need quasi-harmonic entropy correction not entropy 

Can you please explain or give some reading material for same.(I am new in this field)

**Comment by jvalegre** [comment]
Dear Nilesh,

I believe the three papers suggested in my first comment will be quite useful for your questions :
1) Quasi-harmonic correction from Grimme (https://doi.org/10.1002/chem.201200497)
2) GoodVibes paper (https://f1000research.com/articles/9-291)
3) Quasi-harmonic correction for enthalpy from Head-Gordon and coworkers (https://pubs.acs.org/doi/10.1021/jp509921r)

Regarding your questions:
Is that mean reaction mechanism does not require entahlpy correction?
_- Commonly we don't use  quasi-harmonic enthalpy corrections to study reaction mechanisms, we only use quasi-harmonic entropy corrections._

and they why ?
_- The quasi-harmonic correction for enthalpy was originally designed for measuring adsorption enthalpies, treating one component as a surface (which is different from most of the reaction mechanisms that happen in solution phase). Please, check reference number 3 from Head-Gordon and coworkers for a more detailed explanation._

Hope this helps!
Juan

**Comment by nileshjchoudhary** [comment]
Thank Juan, 

I am following the papers
