### ISSUE TITLE
Error in output - unable to run

### ISSUE THREAD

**Issue by NikChekshin** [patonlab/GoodVibes#4]
Dear Rob,

I recently attempted to run the new version of the script on  Python 3.6.2 and Python 2.7.13; every time it would just print an error message saying:

File "GoodVibes.py", line 374
if all_same(l_o_t) == True:
IndentatonError: unexpected indent

This issue seemed to be fixed after I simply deleted two spaces before "if" on line 375 to bring the string to the same block level. However, output still gave an error in both versions of Python but from that point, different versions gave different errors.
I managed to get the script running on Python 2.7.13 (but not on Python 3.6.2) by additionally adding "# -*- coding: utf-8 -*" at the top to enforce UTF-8 and fix the default ASCII encoding problem that caused errors with Python 2.7 (it reported SynthaxError because line 372 apparently contained a non-ASCII '\xc2' character - probably from copy-paste).

Many thanks,
Nik

**Comment by bobbypaton** [comment]
Nik,
Fixed as per your request. Tested with python 2.7 and 3.6 without problem.
Thanks
