### ISSUE TITLE
`.travis-install.sh` syntax error prevents correct Python versions on macOS CI

### ISSUE THREAD

**Issue by berquist** [patonlab/GoodVibes#46]
Because the script is not returning a non-zero error code, its contents are never run, but Travis doesn't halt the build.

https://github.com/bobbypaton/GoodVibes/blob/4b63e5dab2e15a5d13682aee4d75e1f8344338b3/.travis-install.sh#L3
should be
```bash
if [[ $TRAVIS_OS_NAME == 'osx' ]]; then 
```

In #43 I tried fixing this, but discovered that `brew upgrade` causes the macOS builds to time out (> 20 minutes).

**Comment by berquist** [comment]
Now that Travis is basically dead, it's probably better to scrap it completely with a GitHub Actions replacement. I'd be willing to get that started.

**Comment by bobbypaton** [comment]
Travis seems to be working again ...
