### ISSUE TITLE
! Dispersion Correction Failed

### ISSUE THREAD

**Issue by calvanid13** [patonlab/GoodVibes#47]
Dear Robert Paton Group,

I'm writing you because I encountered a message of failed "! Dispersion Correction Failed" (see below) when I used GoodVibes on my optimized Gaussian output using the flag --d3bj for the dispersion estimation (the same failed also with --d3).

Please, could you help me with that or tell me if I did something wrong?

Really Thanks in advance for your work and time.

My Best Regards,

Dario

:~/anthracene/gaussian_analysis/gaussian_dimer$ python -m goodvibes --d3bj anthracene.out
   GoodVibes v3.0.1 2021/07/20 16:49:39
   REF: Luchini, G.; Alegre-Requena J. V.; Guan, Y.; Funes-Ardoiz, I.; Paton, R. S. (2019).
        GoodVibes: GoodVibes 3.0.1 http://doi.org/10.5281/zenodo.595246
   Requested: --d3bj 

   Temperature = 298.15 Kelvin   Pressure = 1 atm
   All energetic values below shown in Hartree unless otherwise specified.
   Using vibrational scale factor 1.0 for PBEPBE/6-31G(d,p) level of theory

   Entropic quasi-harmonic treatment: frequency cut-off value of 100.0 wavenumbers will be applied.
   QS = Grimme: Using a mixture of RRHO and Free-rotor vibrational entropies.
   REF: Grimme, S. Chem. Eur. J. 2012, 18, 9955-9964

   D3-Dispersion energy with Becke-Johnson damping will be calculated and added to the energy terms.
   REF: Grimme S.; Ehrlich, S.; Goerigk, L. J. Comput. Chem. 2011, 32, 1456-1465

   ! Dispersion Correction Failed

   Structure                                           E        ZPE             H        T.S     T.qh-S          G(T)       qh-G(T)
   ********************************************************************************************************************************
o  anthracene                               -1077.780669   0.378979  -1077.379051   0.074184   0.069930  -1077.453235  -1077.448981
   ********************************************************************************************************************************

**Comment by bobbypaton** [comment]
Hi Dario - thanks for the message,

Your command is correct - however, the python code for dftd3 is installed separately from goodvibes for this to work properly.

1. First you should clone or download pydftd3 from here: https://github.com/bobbypaton/pyDFTD3

2. Make sure that the location of this module is then added to your $PYTHONPATH - for example, depending on where you download the repository, you will need to add something like the following line to your .bashrc or .zshrc:

export PYTHONPATH=$PYTHONPATH:/Users/rpaton/Code/pyDFTD3

3. Once that's done your python environment should be able to import dftd3. To check this try python -m dftd3 

4. That's it - goodvibes should now be able to call pydftd3 to get these corrections. 

Sorry it's not easier - we'll look into making this installation a bit more straightforward, e.g. with pip or conda!

**Comment by calvanid13** [comment]
Dear Bobby,

Really Thanks a lot for your fast and clear reply.
I will follow your advice and try the installation also of the pyDFTD3.

My Best Regards,


Dario
