### ISSUE TITLE
Feature Request: CSV Export

### ISSUE THREAD

**Issue by ssiddhantsharma** [patonlab/GoodVibes#48]
Using GoodVibes for my undergrad summer research, I found that one cannot export CSV's with different names or for batch analysis of multiple output files, one cannot save them as an appended single CSV. This would be a nice feature to implement along with the option of exporting just the desired value column from a multiple batch run to a CSV.  

I hope I am articulating my thoughts correctly but would love to go over this in good detail if required.

**Comment by bobbypaton** [comment]
Thanks for the suggestions - just making sure I understand - you would like the following:

(1) ability to name CSVs - sounds easily doable!
(2) ability to append to a CSV that already exists - also doable
(3) ability to select which columns are exported to CSV - if you are doing things with the CSV (e.g. python import using pandas), then couldn't you just drop columns? 

Please feel free to correct my understanding if any or all of the above are not what you meant ..
Thanks

Rob
