### ISSUE TITLE
Symmetry correction of homonuclear diatomic molecules

### ISSUE THREAD

**Issue by RaphaelRobidas** [patonlab/GoodVibes#50]
I was looking at the symmetry correction of homonuclear diatomic molecules, and I am wondering if the rotational entropy correction is being applied twice with `--ssymm`.

In order to calculate the rotational entropy, Goodvibes parses the rotational symmetry number from the Gaussian output file. This seems to always be 1, except for homonuclear diatomic molecules, where it is 2. Goodvibes thus calculates the rotational entropy with this symmetry number. The free energy calculated by Goodvibes is exactly the same as the one in the Gaussian output file.

With the `--ssymm` keyword, Goodvibes applies an additional correction of `RTln(2)` to the free energy. Is that actually correct or is Goodvibes applying a duplicate symmetry correction?

**Comment by jvalegre** [comment]
Thanks we fixed this issue - please, let us know if the problem persists.
