### ISSUE TITLE
SPC energy with double hybrid functional

### ISSUE THREAD

**Issue by npe1011** [patonlab/GoodVibes#51]
Dear developers,

I am using a double hybrid functional method (DSDPBEP86/def2TZVPP) in Gaussian 16 rev.C for single point calculation after opt and freq calculation using a standard hybrid functional (M062X/def2SVP).
When I run goodvibes 3.0.1 to combine the results (using --spc option) to calculate the final free energies, the goodvibes program seemed to read the SCF energy of the DSDPBEP86 results as printed:
 SCF Done:  E(RDSDPBEP86) =  @@@@@@@@     A.U. after    8 cycles
But the correct final EE of double hybrid methods would be the sum of SCF energy and E2 correction after MP2 calculation, as printed:
 E2(DSDPBEP86) =    @@@@@@@@@@@@@@@@@@ E(DSDPBEP86) =    @@@@@@@@@@@@@@@

I would really appreciate if you could check this point.

Accutally, the official GaussView ver 6 seems to read the SCF energy without E2 corrections.

**Comment by jvalegre** [comment]
Hi npe1011 - I just added some lines to account for calculations with double hybrid functionals, could you make sure that GoodVibes is working correctly for you too? The changes are in the latest commit (download + installation through setup.py).

Thanks for reporting this issue!

**Comment by npe1011** [comment]
Thank you very much for a quick reply and change. The new version works fine with my outputs.
