### ISSUE TITLE
Problem with --graph

### ISSUE THREAD

**Issue by andre-cloud** [patonlab/GoodVibes#52]
Hello

I tried to plot two reactions on the same plot, as you've shown in the article 10.12688/f1000research.22758.1

Here is my command
`python -m goodvibes *log --freespace toluene --imag --graph graph.yaml --pes graph.yaml -t 268.15` 

And the graph.yaml file
```
--- # PES
TS_CS : [Pre-RC-II, TS-II, Post-RC-II]
PRC_CS : [Pre-RC-I, TS-I, Post-RC-I]
--- # SPECIES
Pre-RC-I    : pre_rc_opt_freq
Pre-RC-II   : CONF181_pre
TS-I        : TS_displ
TS-II       : CONF181_berny
Post-RC-I   : post_complex_freq
Post-RC-II  : CONF181_post
--- # FORMAT
zero: Pre-RC-I
dec : 2
units : kcal/mol
legend : True 
```

But I get only the first reaction displayed on the graph. Where is the errror? 

Thanks very much

**Comment by luchini18** [comment]
Hi @andre-cloud 
Sorry for the troubles, can you try adding `*` after each name in the `# SPECIES` block
Like this: 
```
--- # SPECIES
Pre-RC-I    : pre_rc_opt_freq*
Pre-RC-II   : CONF181_pre*
TS-I        : TS_displ*
TS-II       : CONF181_berny*
Post-RC-I   : post_complex_freq*
Post-RC-II  : CONF181_post*
```
Also, try removing the `zero` line in `# FORMAT`, it should automatically use the first species in each pathway as the zero.

**Comment by andre-cloud** [comment]
Thanks for the fast and kind reply. 

Without the `zero` flag (and the `*` in the `SPECIES` section) it works fine (it gives me two curves on the graph), but unfortunately, I need that flag because the two reactions must have the same "zero". 
Is it possible?

**Comment by luchini18** [comment]
I see, in that case, you should be able to specify the zero for both 
`zero: Pre-RC-II,Pre-RC-I`

**Comment by andre-cloud** [comment]
But I have to refer TS_RC to PRC_RC and the string `zero : Pre-RC-I, Pre-RC-I` doesn't work, even swapping the order in the `PES` section

**Comment by luchini18** [comment]
Ok, I think I'm understanding. I think the issue with goodvibes is that the `Pre-RC-I` species is not present in the `TS_RC` pathway, and goodvibes won't currently use a species from another pathway as a zero point.

**Comment by luchini18** [comment]
Currently, you could potentially add a dummy calculation that both pathways have in common to use as a zero - it could even be `Pre-RC-I`

**Comment by andre-cloud** [comment]
Really really appreciated all the effort and all the work behind this project. Thanks again for the answer
