### ISSUE TITLE
Remove the higher-energy duplicate with --dup

### ISSUE THREAD

**Issue by aikonens** [patonlab/GoodVibes#54]
I ran GoodVibes with the --dup argument and noticed that it removed the lowest energy conformer – conf_1 – as duplicate instead of the higher energy one – conf_10. The difference is only 0.5–0.6 kcal/mol, but could be changed to remove the higher energy and keep the lower energy ones. Both outputs are in the example.txt

[example.txt](https://github.com/patonlab/GoodVibes/files/8574925/example.txt)

**Comment by bobbypaton** [comment]
This should now be fixed if --sort G is called. The conformers will be sorted based on stability first, and then the conformer appearing first in the ordered list will be retained ...
