### ISSUE TITLE
Acceleration of GV

### ISSUE THREAD

**Issue by jvalegre** [patonlab/GoodVibes#68]
After v3.2, GV started using cclib to extract data, but GV has become quite slow. We can use the original GV parser for Gaussian calcs instead, and use cclib for outputs coming from other QM programs. 

Something that can accelerate quite a bit the original code is to replace the regular loops with inverse loops that break after the SCF energy and the frequencies are read (we could import the code from the initial versions of AQME-QCORR).

**Comment by bobbypaton** [comment]
Will put on the to do list
